describe('Tambah Facilitator', function() {
    it('Login Facilitator', function() {
        cy.loginberhasil()
    }),

    it('Berhasil Tambah Facilitator', function() {
        cy.wait(2000)
        cy.get('.h3 > b')
            .should('have.text', 'Facilitator')
        cy.get('.d-flex > .btn').click()
        cy.get('#user_fullname').type('Xiahou')
            .should('have.value', 'Xiahou')
        cy.get('#user_email').type('xiahou2@gmail.com')
            .should('have.value', 'xiahou2@gmail.com')
        cy.get('#user_is_active')
            .should('have.value', '1')
        cy.get('#user_password').type('1234567')
            .should('have.value', '1234567')
        cy.get('#user_province_id').select('DKI JAKARTA')
            .should('have.value', '31')
        cy.get('#user_city_id').select('KOTA ADM. JAKARTA PUSAT')
            .should('have.value', '3171')
        cy.get('#user_subdistrict_id').select('Tanah Abang')
            .should('have.value', '317107')
        cy.get('#user_address').type('Jl. Tanah Abang No 7, Jakarta Pusat')
            .should('have.value', 'Jl. Tanah Abang No 7, Jakarta Pusat')
        cy.get('.custom-control').click()
        cy.get('input[type="file"]').attachFile('contoh.jpg')
            .should('exist')
        cy.contains('Simpan').click()
        cy.contains('Penambahan fasilitator berhasil diproses')
            .should('have.text', 'Penambahan fasilitator berhasil diproses')
        cy.contains('OK').click()
    }),

    it('Gagal Tambah Facilitator', function() {
        cy.wait(2000)
        cy.get('.h3 > b')
            .should('have.text', 'Facilitator')
        cy.get('.d-flex > .btn').click()
        cy.get('#user_fullname').type('Zilong')
            .should('have.value', 'Zilong')
        cy.get('#user_email').type('zilong@gmail.com')
            .should('have.value', 'zilong@gmail.com')
        cy.get('#user_is_active')
            .should('have.value', '1')
        cy.get('#user_password').type('1234567')
            .should('have.value', '1234567')
        cy.get('#user_province_id').select('DKI JAKARTA')
            .should('have.value', '31')
        cy.get('#user_city_id').select('KOTA ADM. JAKARTA PUSAT')
            .should('have.value', '3171')
        cy.get('#user_subdistrict_id').select('Tanah Abang')
            .should('have.value', '317107')
        cy.get('#user_address').type('Jl. Tanah Abang No 7, Jakarta Pusat')
            .should('have.value', 'Jl. Tanah Abang No 7, Jakarta Pusat')
        cy.get('.custom-control').click()
        cy.get('input[type="file"]').attachFile('contoh.jpg')
            .should('exist')
        cy.wait(3000)
        cy.contains('Simpan').click()
        cy.contains('Email sudah digunakan')
            .should('have.text', 'Email sudah digunakan')
        cy.contains('OK').click()
    })
})
    Cypress.on('uncaught:exception', (err, runnable)=>{
        return false
})